### ISSUE TITLE
Building musl+static+flambda variants

### ISSUE THREAD

**Issue by SquidDev** [ocurrent/docker-base-images#107]
I'm currently trying to clean up some of my Dockerfiles and moving over to the `ocaml/opam` images (I was previously building the switches myself). However, I've a couple of jobs which produce static binaries on Alpine using a `musl+static+flambda` switch.

However, images for this switch aren't currently provided on Docker Hub. What would your thoughts be on also building these?

It may only be worth producing musl+static+flambda images for alpine distributions - not sure how feasible this is thought. I'm not entirely clear on how this, dockerfile_distro and ocaml-version all interact.

**Comment by avsm** [comment]
You don't need a musl variant when you're building on Alpine. It's already using musl as its libc.

**Comment by SquidDev** [comment]
Ahh, thought the `+static` modifier was required, but it's possible it's not. Thanks!
