### ISSUE TITLE
Menhir broken in all ocaml/opam images on DockerHub

### ISSUE THREAD

**Issue by Niols** [ocurrent/docker-base-images#110]
*Apologies if this is not the right place to post this issue.*

I noticed that all the images in https://hub.docker.com/r/ocaml/opam/ have been pushed between Monday 17 and Tuesday 18 this week. Sadly, this happened right:

- after Inria changed the policies of their GitLab, breaking the download links of all the archives of packages by François Pottier including Menhir
- before François got the chance to fix the URLs in OPAM with ocaml/opam-repository#18697

This means that, at the moment, **all** the Docker images of https://hub.docker.com/r/ocaml/opam/ include links to Menhir that are invalid and cause the installation of any software that uses Menhir to fail, which seems rather critical to me considering how widespread the use of this software is.

Would it be possible to regenerate and push all the Docker images in advance? (I have no idea how often you update them and I don't think I can get this information from DockerHub).

**Comment by dra27** [comment]
This is the right place, thanks! The images are now rebuilding (you can see the progress at https://base-images.ocamllabs.io/). They are rebuilt weekly, but they can always be rebuilt on demand when required!

**Comment by avsm** [comment]
Once https://github.com/ocurrent/docker-base-images/issues/99 is fixed, this will not be a problem in the future either, as we cache archives on opam.ocaml.org.
