### ISSUE TITLE
Ubuntu 22.04 / 22.10 images are missing riscv64 architecture

### ISSUE THREAD

**Issue by tmcgilchrist** [ocurrent/docker-base-images#206]
Reported by @mtelvers the Ubuntu images on docker hub are missing riscv 64 support in the latest versions. See https://hub.docker.com/_/ubuntu/tags?page=1&name=22.10 and https://hub.docker.com/_/ubuntu/tags?page=1&name=22.04.

Causing the docker pipeline to fail and our riscv based images to be out of date. Based on the scarcity of riscv hardware we are only really using the riscv hardware for building these images and for some minor testing. We could one of:
 1. Use the oldest published version that did include riscv support
 2. Use an alternative image like https://hub.docker.com/r/riscv64/ubuntu/
 3. Remove publishing images until we get more hardware online and Ubuntu starts publishing docker images again.
 
Option 1 seems reasonable for now. Other than the ocluster-worker and base-image-builder, is anyone else relying on these images? @dra27

**Comment by mtelvers** [comment]
For the latest ocluster worker deployment, we went with option 1, using `FROM ubuntu:jammy-20221130` as that is the latest version which supports riscv.  [Dockerfile.worker](https://github.com/ocurrent/ocluster/blob/64f369d3c4c8e41026b873612411e640e3dad5ac/Dockerfile.worker#L13)

**Comment by dra27** [comment]
What's the "correct" thing here? Should we be using riscv64/ubuntu in general?

**Comment by dra27** [comment]
i.e. is there any information on the change in support of riscv64

**Comment by kit-ty-kate** [comment]
Not much apart from "this is intentional and we're talking about it to possibly bring it back later" https://github.com/docker-library/official-images/pull/13950#issuecomment-1412111952

**Comment by MisterDA** [comment]
I'm suggesting to use the images from riscv64/ubuntu:
- https://github.com/ocurrent/ocaml-dockerfile/pull/150
- https://github.com/ocurrent/docker-base-images/pull/214

**Comment by MisterDA** [comment]
> What's the "correct" thing here? Should we be using riscv64/ubuntu in general?

I've pushed this change, enabling the riscv64 Ubuntu images again (and the multiarch tags as well).

**Comment by tmcgilchrist** [comment]
@benmandrew With the 23.10 upgrade docker base images is missing RiscV support again. See https://images.ci.ocaml.org/job/2023-10-31/060912-ocluster-build-fd0e13

**Comment by benmandrew** [comment]
The Ubuntu build page shows that Mantic has been built successfully on riscv64 and is up-to-date: https://launchpad.net/~cloud-images-release-managers/+livefs/ubuntu/mantic/ubuntu-oci.

The riscv64/ubuntu Docker page hasn't had updates in 10 months. I sent an email a few weeks ago to Steve Langasek (listed on the Launchpad page) about this but I've not had a response. I'll try contacting other members of the team, but it's a little difficult to find who's responsible.

**Comment by shonfeder** [comment]
@mtelvers has work to address this on https://github.com/mtelvers/docker-base-images/pull/1, which PR will to target this repo soon.

**Comment by shonfeder** [comment]
@mtelvers opened https://github.com/ocurrent/docker-base-images/issues/206, which tracks work on a general solution to this problem, so I'll close this in favor of that.
