### ISSUE TITLE
opam master fails to build with MSVC on Windows ltsc2022

### ISSUE THREAD

**Issue by MisterDA** [ocurrent/docker-base-images#218]
<https://images.ci.ocaml.org/job/2023-03-13/135820-ocluster-build-990991>
Make doesn't report a lot of errors. My guess is a problem with Windows / Unix paths when building vendored dependencies.

```
make MAKEFLAGS= -f ../Makefile.packages -C topkg topkg-pkg-build && touch topkg.pkgbuild
make[2]: Entering directory '/tmp/opam-build-master/src_ext/topkg'
ocaml pkg/pkg.ml build --pkg-name topkg --dev-pkg false
mkdir 'C:\cygwin64\tmp\opam-build-master\src_ext\topkg\_build'
The system cannot find the path specified.
```

This error also appears with the mingw build but doesn't fail the build. The error might be somewhere else.

cc @dra27

**Comment by dra27** [comment]
That error is definitely benign - not sure what's happening. I'd probably debug it by manually building up to the previous step in the `Dockerfile` and then running the command manually in a container. A quick check locally with MSVC (not Server 2022, therefore) had `make lib-pkg` working.

Incidentally, for debugging, it's useful to run `make -C src_ext lib-pkg` as that doesn't run with `-j`. I can't remember why you settled on `make lib-pkg` - it may just be easier to do `make compiler` and then let the automatic `src_ext` vendoring in `configure` take over?

**Comment by MisterDA** [comment]
Ha! I couldn't reproduce it locally, and in the meantime, it has disappeared.
