### ISSUE TITLE
An option to provide image with sandboxing?

### ISSUE THREAD

**Issue by Niols** [ocurrent/docker-base-images#229]
Hi there,

How hard would it be to provide an option to _not_ disable sandboxing? I was trying to use these images to check that some packages install fine in OPAM, and my CI was happy although the package in question was downloading from internet during its installation.

I don't mean to make it the default, or even to publish images with sandboxing on, but if it happened to be easy to provide, then that would allow me to build my own images without having to redo all the work that has been done in here.

Best,
-- Nicolas

**Comment by MisterDA** [comment]
I suggest you use the images as-is. Then, there's the script that you can use inside the image, `opam-sandbox-enable`. Run the script, which will just setup `~/.opamrc`, then run `opam init --reinit`.

**Comment by MisterDA** [comment]
Exactly! bubblewrap isn't useful in a container, sandboxing doesn't make much sense in a container either. Our use-case is that with OBuilder, we extract the Docker images to the host filesystem, and we use runc and bubblewrap to provide containerization and sandboxing in a custom way.

**Comment by talex5** [comment]
It will probably work with `docker run --privileged` (but you have to trust the container then).
