### ISSUE TITLE
Application and Operational Metrics

### ISSUE THREAD

**Issue by benmandrew** [ocurrent/docker-base-images#252]
`docker-base-images` should report on application and operational level metrics via prometheus/grafana.

![docker-base-images-monitoring](https://github.com/ocurrent/docker-base-images/assets/13054139/4db4cfdf-15fc-4bd2-8547-f1642c139265)

- [x] Production dashboard in grafana for https://images.ci.ocaml.org
- [x] Setup ocluster connection to export stats (it already supports prometheus)
- [x] Setup ocurrent to export stats (it already supports prometheus)
- [x] Add ocurrent support for exporting Node creation/update/destroy metrics (as a proxy for graph size)

Non-exhaustive list of tasks to cover the monitoring of `docker-base-images` application.

**Comment by mtelvers** [comment]
I have imported https://images.ci.ocaml.org/host/metrics and https://images.ci.ocaml.org/metrics into Prometheus/Grafana at https://status.ocaml.ci.dev.  You can configure your dashboard to use these inputs.  `/metrics` is for OCaml and the application itself, and `/host/metrics` reports on the physical host.  On your dashboard, you can use things like:

```
ocaml_gc_heap_words{instance="images.ci.ocaml.org:443"}
node_load1{instance="images.ci.ocaml.org:443"}
```  

There is a starter 'Base Image Builder' dashboard on status.ocaml.ci.dev

**Comment by benmandrew** [comment]
Application specific metrics were added in https://github.com/ocurrent/docker-base-images/pull/253. Metrics are surfaced on Grafana (https://status.ocaml.ci.dev) under the 'Base Image Builder' dashboard. There are likely more useful metrics to be added, such as the OCurrent Docker plugin metrics added in https://github.com/ocurrent/ocurrent/pull/437, so this issue remains open.

<img width="1431" alt="Screenshot 2023-10-16 at 13 55 25" src="https://github.com/ocurrent/docker-base-images/assets/13054139/ead73860-b06b-4be9-8d99-8ee1257c5fbd">

**Comment by tmcgilchrist** [comment]
https://github.com/ocurrent/ocurrent/pull/437 is merged. I think this can be closed as done @benmandrew do you agree?
![Screenshot 2023-12-12 at 12 21 49 pm](https://github.com/ocurrent/docker-base-images/assets/170937/d3319589-e317-481e-857c-c4f88c18f1d2)

**Comment by benmandrew** [comment]
Agreed.
