### ISSUE TITLE
Build missing base images

### ISSUE THREAD

**Issue by mtelvers** [ocurrent/docker-base-images#276]
Ubuntu supports RISCV. However, they do not always create a Docker base image.  This is notable in #258 and #275 where 23.10 and 24.04 are both missing the RISCV image.  22.04 initially had a RISCV base image, but it was dropped in mid-2022.

Creating a base image is relatively simple as a specific tool is available: `debootstrap`.

Thus, a `Dockerfile` such as presented below would build the missing Docker base images.

```Dockerfile
FROM ubuntu:jammy-20220801 AS base
WORKDIR /base
RUN apt update && apt install -y debootstrap
RUN ln -s gutsy /usr/share/debootstrap/scripts/noble
# 24.04 noble
# 23.10 mantic
# 22.04 jammy
# 20.04 focal
RUN debootstrap noble /base

FROM scratch
COPY --from=base /base /
CMD /bin/bash
```

Build with `docker build -t ubuntu:noble .`

**Comment by mtelvers** [comment]
A suitable PR to achieve this is https://github.com/mtelvers/docker-base-images/pull/1

**Comment by shonfeder** [comment]
Mark reports that there seems to be an issue with the Ubuntu distro version of tar. Getting permission errors.

**Comment by shonfeder** [comment]
iiuc, this is a related problem following from the permissioning changes; https://github.com/ocaml/opam/issues/5968

**Comment by mtelvers** [comment]
Merged in https://github.com/ocurrent/docker-base-images/pull/282
