### ISSUE TITLE
All base image builds have failed

### ISSUE THREAD

**Issue by mtelvers** [ocurrent/docker-base-images#283]
The compilation of opam 2.0 fails in all builds with a MD5 mismatch on `ocamlgraph.tar.gz`

```
#21 2.674 MD5 for ocamlgraph.tar.gz differ:
#21 2.674   expected: 9d71ca69271055bd22d0dfe4e939831a
#21 2.674     actual: 9d1ead73e678fa2f51a70a933b0bf017
#21 2.675 Failed to download http://ocamlgraph.lri.fr/download/ocamlgraph-1.8.8.tar.gz
```

The link for ocamlgraph is broken giving the MD5 mismatch.  Root cause investigations are underway.

**Comment by mtelvers** [comment]
The correct URL is https://github.com/backtracking/ocamlgraph/releases/download/v1.8.8/ocamlgraph-1.8.8.tar.gz

**Comment by mtelvers** [comment]
We are still unable to build Opam due to the outage at Inria.  See https://github.com/ocaml/ocaml/issues/13237

```
20 6.138 Turn off this advice by setting config variable advice.detachedHead to false
#20 6.138 
#20 6.138 HEAD is now at 62ad0c217 Merge pull request #6026 from kit-ty-kate/fix-10-menu-options
#20 136.7 curl: (28) Failed to connect to caml.inria.fr port 443 after 130580 ms: Couldn't connect to server
```

**Comment by shonfeder** [comment]
Most are building now, thanks to your updates (see https://github.com/ocaml/infrastructure/issues/128): https://status.ocaml.ci.dev/d/f0622ee4-9404-417c-97dc-3cd40d6ac34b/base-image-builder?orgId=1&refresh=10s&from=1719346856002&to=1719368456003

There are other failures now, but they appear to be issues with specific architectures and ocaml version.
