### ISSUE TITLE
"latest distribution" images are missing

### ISSUE THREAD

**Issue by kit-ty-kate** [ocurrent/docker-base-images#73]
`ocaml/opam2` used to have `<distro>-ocaml-<ver>` images as an alias of `<distro>-<distro-latest-ver>-ocaml-<ver>`

Required for `ocaml-ci-scripts`. In the meantime I've added an ugly hack to make it work: https://github.com/ocaml/ocaml-ci-scripts/pull/350

**Comment by avsm** [comment]
Yes we should definitely generate these. For instance `alpine-ocaml-4.11` is a lot more future proof for generic uses of musl that `alpine-3.12-ocaml-4.11`

**Comment by talex5** [comment]
(aliases are currently being pushed: https://base-images.ocamllabs.io/jobs)
