### ISSUE TITLE
consider adding MVP docs and or links to dockerhub

### ISSUE THREAD

**Issue by cdaringe** [ocurrent/docker-base-images#98]
# Problem

https://hub.docker.com/r/ocaml/opam lacks description and content:

<img width="634" alt="image" src="https://user-images.githubusercontent.com/1003261/112562955-b28a8c80-8d95-11eb-9815-6dffda273c63.png">

# Solution

Add a description. Here's just an idea for some content

```md
# OCaml Platform Docker Images

OCaml images are built using `opam` tooling, and come bundled with `opam` and your desired compiler version.  These images were previously hosted at [ocaml/opam2](...).

Images tags take one of the following forms:

- `<OS>`
- `<OS>-ocaml-<OCAML_VERSION>`
- `<OS>-<OS_VERSION>-ocaml-<OCAML_VERSION>`
- `<OS>-<OS_VERSION>-ocaml-<OCAML_VERSION>-<VARIANT>`
- ...

*warning*: `OCAML_VERSION` drops the patch version, and carries only major.minor values, like `4.06`, vs `4.06.1.` 
<!-- ^ there's probably a better descriptor to use here, and a more complete one -->

- See [the tags page](https://hub.docker.com/r/ocaml/opam/tags) to find an image suited to your needs
- See [ocurrent/docker-base-images](https://github.com/ocurrent/docker-base-images) to see how these images are built

## Example

`docker run --rm ocaml/opam:alpine-ocaml-4.11 opam switch show`
```

**Comment by cdaringe** [comment]
OH, also worthy of mention is that `opam` isn't pointing to `opam.org`? that tripped me up some

**Comment by dra27** [comment]
Thanks, @cdaringe - there should definitely be some content on the Hub page, which we're now working on 🙂

**Comment by dra27** [comment]
The opam remote is an interesting question worthy of it's own tracking issue which I'll shortly open...

**Comment by dra27** [comment]
Apologies for the delay (which was down to getting around to reviewing it...), but the text on Docker Hub has now been updated!
